### ISSUE TITLE
CI job fails with Module "jspm.dev/xlsx" has no default export

### ISSUE THREAD

**Issue by ribtoks** [githubocto/flat#72]
Hi

Thanks for working on `flat`. Recently my [pipeline](https://github.com/Xpiks/flat/blob/master/.github/workflows/flat.yml) started [failing](https://github.com/Xpiks/flat/runs/5261889945?check_suite_focus=true) with the following error:

```
Warning Implicitly using latest version (1.0.0) for [deno.land/x/url_join/mod.ts](https://deno.land/x/url_join/mod.ts)
  Error: Error: Command failed: NO_COLOR=true deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable postprocess.js data-raw.json
  Warning Implicitly using latest version (1.0.0) for [deno.land/x/url_join/mod.ts](https://deno.land/x/url_join/mod.ts)
  Error: TS1192 [ERROR]: Module '"[jspm.dev/xlsx](https://jspm.dev/xlsx)"' has no default export.
  import xlsxlib from '[jspm.dev/xlsx](https://jspm.dev/xlsx)'
         ~~~~~~~
      at [deno.land/x/flat@0.0.11/src/xlsx.ts:1:8](https://deno.land/x/flat@0.0.11/src/xlsx.ts:1:8)
  
  Error: TS1192 [ERROR]: Module '"[jspm.dev/xlsx](https://jspm.dev/xlsx)"' has no default export.
  import xlsxlib from '[jspm.dev/xlsx](https://jspm.dev/xlsx)'
         ~~~~~~~
      at [deno.land/x/flat@0.0.11/src/xlsx.ts:1:8](https://deno.land/x/flat@0.0.11/src/xlsx.ts:1:8)
```

Please advice how to fix.

**Comment by irealva** [comment]
Hi there, please upgrade your version of the post-processing library to: `flat@0.0.14` and that should fix it! 

More info here: #67.

**Comment by ribtoks** [comment]
Thanks, it fixes the problem!
